//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluDay.Net.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluDay.Net.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} is already targeted by another argument..
        /// </summary>
        internal static string CONFLICITNG_ARGUMENT_TARGET_PROPERTY {
            get {
                return ResourceManager.GetString("CONFLICITNG_ARGUMENT_TARGET_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag name &quot;{0}&quot; must be exlusively alphanumeric..
        /// </summary>
        internal static string INVALID_ARGUMENT_FLAG_NAME {
            get {
                return ResourceManager.GetString("INVALID_ARGUMENT_FLAG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument position for &quot;{0}&quot; must be zero or greater..
        /// </summary>
        internal static string INVALID_ARGUMENT_TOKEN_POSITION {
            get {
                return ResourceManager.GetString("INVALID_ARGUMENT_TOKEN_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long flag name &quot;{0}&quot; must be longer than short name &quot;{1}&quot;..
        /// </summary>
        internal static string INVALID_LONG_ARGUMENT_FLAG_LENGTH {
            get {
                return ResourceManager.GetString("INVALID_LONG_ARGUMENT_FLAG_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized argument flag &quot;{0}&quot;..
        /// </summary>
        internal static string UNRECOGNIZED_ARGUMENT_FLAG {
            get {
                return ResourceManager.GetString("UNRECOGNIZED_ARGUMENT_FLAG", resourceCulture);
            }
        }
    }
}
